---
# file: ansible-home/group_vars/all.yml

#ansible_become: yes
#ansible_become_method: sudo
#ansible_become_pass: "{{ ansible_user_password }}"

users:
  - username: ansible
    role: admin
    sudo: pass
    gecos: Ansible service
    shell: /bin/bash
    home: yes
    update_pass: always

vault_id_labels:
  - prov
  - dev
  - stage
  - prod