---
# file: ansible-home/configure-ansible.yml

- name: Configure ansible server
  hosts: localhost

  vars_prompt:
  - name: "ssh_passphrase"
    prompt: "Ansible ssh passphrase"
    private: yes
    confirm: yes

  roles:
    - ansible