---
# file: ansible-home/configure-ansible.yml

- name: Configure ansible server
  hosts: localhost

  vars:
    centralized_authentification: false
    users:
      - { role: admin, sudo: pass, username: ansible, gecos: Ansible service, shell: /bin/bash }

  vars_prompt:
  - name: "ssh_passphrase"
    prompt: "Ansible ssh passphrase"
    private: yes
    confirm: yes

  roles:
    - ansible