---
# file: ansible-home/configure-ansible.yml

- name: Configure ansible server
  hosts: localhost

  vars:
    centralized_authentification: false
    users:
      - { role: admin, sudo: nopass, username: ansible, gecos: Ansible service, shell: /bin/bash }
    packages_common:
      - sudo
      - openssl

  vars_prompt:
  - name: "ssh_passphrase"
    prompt: "Ansible ssh passphrase"
    private: yes
    confirm: yes

  tasks:
  - name: Install packages "{{ item }}"
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - "{{ packages_common }}"
    tags:
      - install

  - include: "{{ playbook_dir }}/tasks/users.yml"
    with_items:
      - "{{ users }}"
    tags:
      - users

  - include: "{{ playbook_dir }}/tasks/ansible.yml"
    with_items:
      - "{{ users }}"
    tags:
      - ansible