---
# file: ansible-home/roles/common/tasks/users.yml

- name: Generate '{{ item.username }}' user password
  shell: openssl rand -base64 48
  register: user_passwd_reg

- name: Set '{{ item.username }}' user password variable
  set_fact:
    user_passwd: "{{ user_passwd_reg.stdout }}"
    cacheable: no
  when: user_passwd_reg is succeeded
  register: password_fact_set
    
- name: Add user '{{ item.username }}'
  user:
    name: "{{ item.username }}"
    comment: "{{ item.gecos }}"
    shell: "{{ item.shell }}"
    create_home: yes
    password: "{{ user_passwd | password_hash('sha512') }}"
    update_password: on_create
  when: password_fact_set is succeeded

- name: Update '{{ item.username }}' user password
  user:
    name: "{{ item.username }}"
    password: "{{ user_passwd | password_hash('sha512') }}"
    update_password: always
  when: item.username == 'ansible'
  tags:
    - ansible

- name: Save client ansible password block
  block:
  - name: Set '{{ item.username }}' user password file variable
    set_fact:
      user_passwd_path: "/etc/ansible/.passwd/{{ item.username }}.{{ inventory_hostname }}.yml"
      cacheable: no

  - name: Save remote '{{ item.username }}' user password
    copy:
      dest: "{{ user_passwd_path }}"
      content: |
        ---
        # file: {{ user_passwd_path }}
        ansible_become_pass: {{ user_passwd }}

  - name: Encrypt '{{ item.username }}' user password file
    command: "ansible-vault encrypt {{ user_passwd_path }}"

  - name: Set permission to '{{ item.username }}' user password file
    file:
      path: "{{ user_passwd_path }}"
      owner: "{{ item.username }}"
      group: "{{ item.username }}"
      mode: 0400
# END Save client ansible password block
  when: item.username == 'ansible'
  delegate_to: 127.0.0.1
  tags:
    - ansible