---
# file: ansible-home/roles/ansible/tasks/main.yml

- name: Install {{ role_name }} packages
  package:
    name: "{{ packages_ansible }}"
    state: latest
  tags:
    - install

- name: Create ansible dir
  file:
    path: /etc/ansible/.passwd
    state: directory
    owner: root
    group: root
  tags:
    - ansible

- include: "{{ playbook_dir }}/tasks/users.yml"
  with_items:
    - "{{ users }}"
  tags:
    - users

- include: ssh-keys.yml
  when: item.username == 'ansible'
  with_items:
    - "{{ users }}"
  tags:
    - ansible

- name: Create vault pass dir
  file:
    path: /home/ansible/.vault_pass
    state: directory
    owner: ansible
    group: ansible
    mode: 0700
  tags:
    - vaultid

- include: vault-pass.yml
  with_items: "{{ vault_id_labels }}"
  tags:
    - vaultid