---
# file: ansible-home/roles/common/tasks/ssh-keys.yml

- name: Set fact ssh socket dir
  set_fact:
    ssh_socket_dir: .ssh/cm_socket

- name: Generate '{{ item.username }}' user ssh keys
  user:
    name: "{{ item.username }}"
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_type: rsa
    ssh_key_file: .ssh/id_rsa
    ssh_key_passphrase: "{{ ssh_passphrase }}"

- name: Configure ssh-client for '{{ item.username }}' user
  copy:
    dest: "/home/{{ item.username }}/.ssh/config"
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: 0644
    content: |
      Host *
        Compression yes
        ServerAliveInterval 30m
        ServerAliveCountMax 1
        ControlMaster auto
        ControlPath ~/{{ ssh_socket_dir }}/%r@%h:%p
        ControlPersist 30m

- name: Create ssh socket directory
  file:
    state: directory
    path: "/home/{{ item.username }}/{{ ssh_socket_dir }}/"
    owner: "{{ item.username }}"
    group: "{{ item.username }}"