---
# file: ansible-home/roles/common/tasks/main.yml

- name: Install {{ role_name }} packages
  package:
    name: "{{ packages_common }}"
    state: latest
  tags:
    - install

- include: "{{ playbook_dir }}/tasks/users.yml"
  with_items:
    - "{{ users }}"
  tags:
    - users

- include: sudo.yml
  with_items:
    - "{{ sudoers_dir_files }}"
  tags:
    - sudo

- include: dot-files.yml
  when: outer_item.username != 'ansible'
  with_items:
    - "{{ users }}"
  loop_control:
    loop_var: outer_item
  tags:
    - dotfiles