---
# file: ansible-home/roles/common/tasks/main.yml

- name: Update repositories with apt
  apt:
    update_cache: yes
  when: ansible_facts['os_family'] == "Debian"
  tags:
    - update

- name: Update all packages with apt
  apt:
    update_cache: yes
    upgrade: dist
  when: ansible_facts['os_family'] == "Debian"
  tags:
    - upgrade

- name: Install {{ role_name }} packages
  package:
    name: "{{ packages_common }}"
    state: present
  tags:
    - install

- name: Include add user
  include_tasks:
    file: "{{ playbook_dir }}/tasks/users.yml"
  when: centralized_authentification == false
  with_items:
    - "{{ users }}"
  tags:
    - users

- name: Include sudo tasks
  include_tasks: sudo.yml
  with_items:
    - "{{ sudoers_dir_files }}"
  tags:
    - sudo