---
# file: ansible-home/roles/common/tasks/main.yml

- name: Update repositories with apt
  apt:
    update_cache: yes
  tags:
    - update

- name: Upgrade all packages with apt
  apt:
    update_cache: yes
    upgrade: dist
  tags:
    - upgrade

- name: Install {{ role_name }} packages
  package:
    name: "{{ packages_common }}"
    state: present
  tags:
    - install

- include: "{{ playbook_dir }}/tasks/users.yml"
  with_items:
    - "{{ users }}"
  tags:
    - users

- include: dot-files.yml
  when: outer_item.username != 'ansible'
  with_items:
    - "{{ users }}"
  loop_control:
    loop_var: outer_item
  tags:
    - dotfiles

- name: Include sudo tasks
  include: sudo.yml
  with_items:
    - "{{ sudoers_dir_files }}"
  tags:
    - sudo