---
# file: ansible-home/roles/common/tasks/sudo.yml

- name: Copy sudoers file
  copy:
    dest: "{{ sudoers_file_path }}"
    src: sudoers.txt
    owner: root
    group: root
    mode: 0600
    backup: yes

- name: Ensure sudoerd.d exists
  file:
    path: "{{ sudoers_dir_path }}"
    state: directory
    owner: root
    group: root

- name: Install sudoers.d file "{{ item }}"
  template:
    dest: "{{ sudoers_dir_path }}/{{ item }}"
    src: "{{ item }}.j2"
    owner: root
    group: root
    mode: 0600