---
# file: ansible-home/host_vars/localhost.yml

#ansible_user: root
ansible_connection: local
ansible_become_pass: false

users:
  - username: ansible
    role: admin
    sudo: pass
    gecos: Ansible service
    shell: /bin/bash
    home: yes
    update_pass: always
  - username: olegdeb
    role: admin
    sudo: pass
    gecos: Oleg Rom
    shell: /bin/bash
    home: yes
    update_pass: on_create